# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the windows-orb
  # #NEEDED RN for .net framework builds
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: 
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run: nuget restore .\sample
      - run: msbuild .\sample
      - run:  
          name: Compressing Files
          command: |
           $ProgressPreference = "SilentlyContinue"
           Compress-Archive -Path .\sample\sample\bin -DestinationPath .\sample\archive
      - run: ls .\sample
      - store_artifacts:
          path: .\sample\archive